name: SecuritySMP
version: ${project.version}
main: me.swipez.securitysmp.SecuritySMP
api-version: 1.16
authors: [ notnotnotswipez ]
commands:
  bal:
    usage: /bal
    description: Shows you how much money you have in your inventory
  givemoney:
    usage: /givemoney <player> <amount>
    description: Gives player specified money
  itemsmenu:
    usage: /itemsmenu
    description: Opens menu of all items
  team:
    usage: /team
    description: Team command
